// Flatten the modular css/*.css into a single portable lab.css, in two
// forms:
//   - flattenRethemable: real CSS concatenated, the 6 seed values substituted,
//     calc()/var() preserved (auto-tracks tokens.css, cannot drift).
//   - flattenStatic: same concat, seeds block removed, every derived color
//     declaration rewritten to its AA-adjusted hsl() literal; non-color lines
//     verbatim. No calc(), no --nc-seed-*.
//
// Tailwind is intentionally excluded (app-only utility layer).

import { hslToString, type DerivedTheme, type HSL, deriveAll } from "./derive";
import { buildAdjustedThemes } from "./wcag";

// Raw CSS chunks, imported verbatim by Vite. Order mirrors lab.css
// minus the Tailwind lines (@import "tailwindcss" and lab.tailwind.css).
import seedsRaw from "../../css/lab.seeds.css?raw";
import tokensRaw from "../../css/lab.tokens.css?raw";
import fontsRaw from "../../css/lab.fonts.css?raw";
import resetRaw from "../../css/lab.reset.css?raw";
import buttonsRaw from "../../css/lab.buttons.css?raw";
import consoleRaw from "../../css/lab.console.css?raw";
import controlsRaw from "../../css/lab.controls.css?raw";
import datadisplayRaw from "../../css/lab.datadisplay.css?raw";
import decorationRaw from "../../css/lab.decoration.css?raw";
import diagramRaw from "../../css/lab.diagram.css?raw";
import feedbackRaw from "../../css/lab.feedback.css?raw";
import inputsRaw from "../../css/lab.inputs.css?raw";
import instrumentRaw from "../../css/lab.instrument.css?raw";
import layoutRaw from "../../css/lab.layout.css?raw";
import markdownRaw from "../../css/lab.markdown.css?raw";
import navigationRaw from "../../css/lab.navigation.css?raw";
import typographyRaw from "../../css/lab.typography.css?raw";

/** Strip nested `@import ...;` lines from a raw chunk. */
function stripImports(css: string): string {
    return css.replace(/^[ \t]*@import[^;]*;[ \t]*\r?\n?/gim, "");
}

const HEADER =
    "/* Lab design system — flattened single-file build.\n" +
    " * Generated by the Lab generator. Tailwind excluded. */\n\n";

// Component sheets in lab.css order (post-tokens/fonts/reset).
const COMPONENT_CHUNKS = [
    buttonsRaw,
    consoleRaw,
    controlsRaw,
    datadisplayRaw,
    decorationRaw,
    diagramRaw,
    feedbackRaw,
    inputsRaw,
    instrumentRaw,
    layoutRaw,
    markdownRaw,
    navigationRaw,
    typographyRaw,
];

/** Substitute the 6 seed channel values into the seeds block text. */
function substituteSeeds(seedsCss: string, seed: HSL, accent: HSL): string {
    return seedsCss
        .replace(/(--nc-seed-h:\s*)[^;]+;/, `$1${seed.h};`)
        .replace(/(--nc-seed-s:\s*)[^;]+;/, `$1${seed.s};`)
        .replace(/(--nc-seed-l:\s*)[^;]+;/, `$1${seed.l};`)
        .replace(/(--nc-accent-h:\s*)[^;]+;/, `$1${accent.h};`)
        .replace(/(--nc-accent-s:\s*)[^;]+;/, `$1${accent.s};`)
        .replace(/(--nc-accent-l:\s*)[^;]+;/, `$1${accent.l};`);
}

function joinChunks(parts: string[]): string {
    return parts.map((p) => stripImports(p).trim()).join("\n\n") + "\n";
}

/**
 * Rethemable: concatenate real CSS, substitute seeds, keep calc()/vars.
 * Equivalent to the legacy tauri template but auto-tracking tokens.css.
 */
export function flattenRethemable(seed: HSL, accent: HSL): string {
    const seeds = substituteSeeds(stripImports(seedsRaw).trim(), seed, accent);
    return (
        HEADER +
        joinChunks([
            seeds,
            tokensRaw,
            fontsRaw,
            resetRaw,
            ...COMPONENT_CHUNKS,
        ])
    );
}

/**
 * Rewrite every derived color declaration inside a `:root { ... }` (or
 * `[data-theme="dark"] { ... }`) block with its computed hsl() literal.
 * Non-color declarations are left verbatim. Operates on the block BODY.
 */
function rewriteBlockBody(body: string, theme: DerivedTheme): string {
    // Split into declarations on top-level `;` (none of our values contain
    // a bare `;`), preserving inter-declaration whitespace by re-joining.
    // We rebuild by replacing each known property's value span.
    let out = body;
    for (const name in theme) {
        const literal = hslToString(theme[name]);
        // Match `--name : <value> ;` where value may span lines / nested parens.
        const re = new RegExp(
            `(${escapeRe(name)}\\s*:)[\\s\\S]*?(;)`,
            "g",
        );
        out = out.replace(re, `$1 ${literal}$2`);
    }
    return out;
}

function escapeRe(s: string): string {
    return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Static: concat (no seeds block), rewrite color tokens to concrete hsl()
 * for both the light `:root{}` and the `[data-theme="dark"]{}` segments.
 * When useWCAG is true, AA-adjusted colors are used; otherwise raw derived.
 * Result has no calc( and no --nc-seed-*.
 */
export function flattenStatic(
    seed: HSL,
    accent: HSL,
    useWCAG = true,
): string {
    const { light, dark } = useWCAG
        ? buildAdjustedThemes(seed, accent)
        : deriveAll(seed, accent);

    let tokens = stripImports(tokensRaw);

    // Rewrite the first :root { ... } block (light theme).
    tokens = replaceFirstBlock(tokens, /:root\s*\{/, (body) =>
        rewriteBlockBody(body, light),
    );
    // Rewrite the dark block.
    tokens = replaceFirstBlock(
        tokens,
        /:root\[data-theme="dark"\]\s*,\s*\[data-theme="dark"\]\s*\{/,
        (body) => rewriteBlockBody(body, dark),
    );

    return (
        HEADER +
        joinChunks([tokens, fontsRaw, resetRaw, ...COMPONENT_CHUNKS])
    );
}

/**
 * Find the first `{ ... }` block whose opening matches `openRe`, transform its
 * body, and splice it back. Brace-aware so nested {} (none here, but safe).
 */
function replaceFirstBlock(
    css: string,
    openRe: RegExp,
    transform: (body: string) => string,
): string {
    const m = openRe.exec(css);
    if (!m) return css;
    const start = m.index + m[0].length;
    let depth = 1;
    let i = start;
    for (; i < css.length; i++) {
        const ch = css[i];
        if (ch === "{") depth++;
        else if (ch === "}") {
            depth--;
            if (depth === 0) break;
        }
    }
    const body = css.slice(start, i);
    return css.slice(0, start) + transform(body) + css.slice(i);
}

// ── Export helper (Tauri save dialog + browser-download fallback) ─────────

export async function exportFile(
    content: string,
    defaultName: string,
    mimeType = "text/css",
): Promise<void> {
    try {
        const { save } = await import("@tauri-apps/plugin-dialog");
        const { writeTextFile } = await import("@tauri-apps/plugin-fs");
        const filePath = await save({
            defaultPath: defaultName,
            filters: [{ name: "CSS", extensions: ["css"] }],
        });
        if (filePath) {
            await writeTextFile(filePath, content);
            console.log(`Exported: ${filePath}`);
        }
    } catch {
        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = defaultName;
        a.click();
        URL.revokeObjectURL(url);
    }
}
